### ISSUE TITLE
Use the $metadataPath parameter

### ISSUE THREAD

**Issue by RobinARH** [microsoft/fin-ops-doc-scripts#2]
The $metadataPath parameter is not used, the hardcoded path “C:\AOSService\PackagesLocalDirectory” is used instead.

A good solution would be to create a single method so that you only have to change the metadataPath in once place to run all the reports.

**Comment by rajatdiptabiswas** [comment]
Hi @RobinARH, I'd like to take a look at this issue.
Is this still available to be worked on?

**Comment by RobinARH** [comment]
Yes, it is. Did you want this to be a Hacktoberfest project? If so, let me make sure that I've got the right tables for this year.

**Comment by RobinARH** [comment]
@rajatdiptabiswas  It's all set up!

**Comment by rajatdiptabiswas** [comment]
Thanks a lot!
I'll get this done as soon as possible.

**Comment by rajatdiptabiswas** [comment]
Hello @RobinARH,
I was busy with an exam this past month and this completely slipped my mind. I am extremely sorry.

```

**Comment by rajatdiptabiswas** [comment]
Hello @RobinARH,
I was busy with an exam this past month and this completely slipped my mind. I am extremely sorry.

I have noticed most of the functions pass in `"C:\AOSService\PackagesLocalDirectory"` to `Get-AxMetadataProvider` in the `BEGIN` section instead of using the function's own `$metadataPath` param.
```powershell
BEGIN {
    $metadataProvider = Get-AxMetadataProvider -metadataPath "C:\AOSService\PackagesLocalDirectory"
}
```

I am assuming we want it to be more dynamic? Something akin to the following?
```powershell
BEGIN {
    $metadataProvider = Get-AxMetadataProvider -metadataPath $metadataPath
}
```

Furthermore, the functions defined in each `.ps1` file are being called at the end of the file by passing in `"C:\AOSService\PackagesLocalDirectory"`. Do those need to be handled as well?

Plus, I can't figure out how to test whether the changes I am making will work. Do I need to install Dynamics 365 Finance?
I tried using PowerShell ISE on my old Windows machine but that got me more confused.
Since I have not worked on PowerShell scripting before, it's quite exciting to learn but kind of difficult to grasp as well.

Do you have any suggestions as to what changes need to be made?

Thank you for your patience.

**Comment by RobinARH** [comment]
Sorry for the delay from me. Yes, you'll need Dynamics 365 Finance. However, we're rethinking this report. So I'm closing this for now. Thank you for the time you spent on this. I appreciate it. -Robin

**Comment by rajatdiptabiswas** [comment]
No worries. You're welcome @RobinARH!
